name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * * # Daily at midnight

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: 'latest'
          configurationFile: '.github/renovate.json'
